export type Taxonomy = {
  [domain: string]: {
    [field: string]: string[];
  };
};

export const TAXONOMY: Taxonomy = {
  "Formal Sciences": {
    "Mathematics": [
      "Symmetry & Structure",
      "The Nature of Infinity",
      "Proof & Mathematical Rigor",
      "Abstraction & Generalization",
      "Pattern & Randomness",
      "Continuous vs Discrete",
      "Unsolvability & Incompleteness",
      "Duality & Correspondence",
      "The Unreasonable Effectiveness of Mathematics",
      "Counting, Combinations & Arrangement",
    ],
    "Computer Science": [
      "Computation & Its Limits",
      "Efficiency & Complexity",
      "Abstraction & Encapsulation",
      "Intelligence & Learning",
      "Information & Communication",
      "Correctness & Verification",
      "Concurrency & Parallelism",
      "Security & Trust",
      "Algorithms as Problem-Solving",
      "The Human-Machine Interface",
    ],
    "Statistics & Probability": [
      "Uncertainty & Chance",
      "Inference from Incomplete Data",
      "Correlation vs Causation",
      "The Law of Large Numbers",
      "Bayesian vs Frequentist Reasoning",
      "Bias, Variance & Model Fit",
      "Randomness & Its Uses",
      "The Central Limit Theorem",
      "Statistical Significance & Its Misuses",
      "Prediction & Forecasting",
    ],
    "Logic": [
      "Truth, Validity & Soundness",
      "The Nature of Proof",
      "Self-Reference & Paradox",
      "Formal Systems & Their Limits",
      "Deduction vs Induction",
      "Possibility & Necessity",
      "The Boundary of the Knowable",
      "Language & Logical Form",
      "Foundations of Mathematics",
      "Computation & Logic",
    ],
  },
  "Natural Sciences": {
    "Physics": [
      "Symmetry & Conservation Laws",
      "The Quantum & the Classical",
      "Space, Time & Relativity",
      "Energy, Entropy & the Arrow of Time",
      "Forces & Fields",
      "The Structure of Matter",
      "Emergence & Complexity",
      "Determinism vs Uncertainty",
      "The Cosmological Scale",
      "Wave-Particle Duality",
    ],
    "Chemistry": [
      "The Nature of Chemical Bonds",
      "Energy in Chemical Reactions",
      "Structure Determines Function",
      "Equilibrium & Dynamic Processes",
      "Acids, Bases & Proton Transfer",
      "Molecular Recognition & Selectivity",
      "Chirality & Symmetry",
      "Oxidation & Reduction",
      "The Periodic Table as a Map",
      "From Molecules to Life",
    ],
    "Biology": [
      "Evolution by Natural Selection",
      "The Cell as the Unit of Life",
      "Genetic Information Flow",
      "Structure & Function",
      "Homeostasis & Regulation",
      "Predator & Prey Dynamics",
      "Cooperation & Competition",
      "Adaptation to Environment",
      "The Origin of Complexity",
      "Life's Chemical Basis",
    ],
    "Earth Sciences": [
      "Deep Time & Geological Change",
      "Plate Tectonics & Planetary Dynamics",
      "Climate & Its Drivers",
      "The Rock Cycle",
      "Water & the Hydrological Cycle",
      "Natural Disasters & Their Causes",
      "The Fossil Record",
      "Soil, Life & Ecosystems",
      "Ocean Systems",
      "Earth as a Coupled System",
    ],
    "Astronomy & Cosmology": [
      "The Scale of the Universe",
      "The Life Cycle of Stars",
      "Dark Matter & Dark Energy",
      "The Big Bang & Cosmic History",
      "Galaxies & Large-Scale Structure",
      "Black Holes & Extreme Gravity",
      "Exoplanets & the Search for Life",
      "The Cosmic Microwave Background",
      "Gravity & Orbital Mechanics",
      "The Fate of the Universe",
    ],
  },
  "Social Sciences": {
    "Economics": [
      "Supply, Demand & Price",
      "Incentives & Human Behavior",
      "Market Failure & Intervention",
      "Growth & Development",
      "Money, Credit & Financial Systems",
      "Rationality vs Irrationality",
      "The Role of Institutions",
      "Trade, Specialisation & Globalisation",
      "Inequality & Distribution",
      "Information Asymmetry & Decision Making",
    ],
    "Psychology": [
      "The Unconscious Mind",
      "Social Influence & Conformity",
      "Memory & Its Distortions",
      "Development Across the Lifespan",
      "The Nature of Personality",
      "Emotion, Motivation & Drive",
      "Mental Health & Illness",
      "Perception vs Reality",
      "The Self & Identity",
      "Nature vs Nurture",
    ],
    "Sociology": [
      "Social Structure & Human Agency",
      "Class, Status & Power",
      "Deviance & Social Control",
      "Collective Action & Social Movements",
      "Race, Gender & Inequality",
      "Family, Kinship & Community",
      "Modernity & Its Discontents",
      "Globalisation & Social Change",
      "Religion & Society",
      "Culture & Identity",
    ],
    "Political Science": [
      "Power & Its Legitimacy",
      "Democracy & Its Challenges",
      "The State & Its Functions",
      "War & International Order",
      "Justice & Rights",
      "Ideology & Political Thought",
      "Interest Groups & Collective Action",
      "Political Economy",
      "Nationalism & Identity",
      "Comparative Government",
    ],
    "Anthropology": [
      "Culture & Its Transmission",
      "Kinship & Social Organisation",
      "Ritual, Myth & Symbol",
      "Language & Culture",
      "The Other & Ethnocentrism",
      "Human Evolution & Prehistory",
      "Exchange & Reciprocity",
      "The Sacred & the Profane",
      "Colonialism & Its Legacy",
      "Material Culture & Objects",
    ],
  },
  "Humanities": {
    "Philosophy": [
      "What Can We Know?",
      "What Is Real?",
      "How Should We Live?",
      "Free Will vs Determinism",
      "The Nature of Mind & Consciousness",
      "Justice & Political Legitimacy",
      "Language & Meaning",
      "Reason & Its Limits",
      "The Existence of God",
      "The Nature of Beauty",
    ],
    "History": [
      "Progress & Decline",
      "The Role of Individuals vs Structures",
      "Power & Its Exercise",
      "Revolution & Change",
      "Memory & Historical Narrative",
      "War & Its Causes",
      "Empire & Colonialism",
      "Economic Forces in History",
      "Contingency vs Necessity",
      "How Societies Define the Other",
    ],
    "Literature": [
      "Identity & Self-Discovery",
      "Love & Its Complications",
      "Power & Corruption",
      "Death, Loss & Grief",
      "The Individual vs Society",
      "Memory & the Past",
      "Innocence & Experience",
      "The Nature of Evil",
      "Redemption & Transformation",
      "The Hero's Journey",
    ],
    "Philosophy of Science": [
      "What Makes a Theory Scientific?",
      "Causation & Explanation",
      "Scientific Realism vs Anti-Realism",
      "Reduction & Emergence",
      "The Role of Experiment",
      "Paradigms & Scientific Revolutions",
      "Values in Science",
      "Probability & Confirmation",
      "Models & Their Relationship to Reality",
      "Science & Its Social Context",
    ],
    "Linguistics": [
      "Language & Thought",
      "How Children Acquire Language",
      "Language Change Over Time",
      "Universals vs Diversity",
      "Meaning & Context",
      "Language & Power",
      "Metaphor & Framing",
      "Bilingualism & Code-Switching",
      "The Writing System",
      "Language & Identity",
    ],
  },
  "Applied Sciences": {
    "Engineering": [
      "Design Under Constraint",
      "Failure & Its Lessons",
      "Scale, Complexity & Systems",
      "Energy Conversion & Efficiency",
      "Materials & Their Properties",
      "Safety, Risk & Redundancy",
      "Human Factors & Ergonomics",
      "Sustainability & Environment",
      "Innovation, Iteration & Prototyping",
      "Trade-offs & Optimisation",
    ],
    "Medicine & Health": [
      "The Body as a System",
      "Disease & Its Causes",
      "Diagnosis, Evidence & Uncertainty",
      "The Immune System & Defence",
      "Mental & Physical Health",
      "Drug Action & Side Effects",
      "Public Health & Prevention",
      "Ageing & Chronic Disease",
      "The Ethics of Medicine",
      "Genetics, Environment & Disease",
    ],
    "Finance": [
      "Risk & Return",
      "Time Value of Money",
      "Market Efficiency & Its Limits",
      "Valuation & Pricing",
      "Leverage & Its Dangers",
      "Diversification & Portfolio Theory",
      "Financial Crises & Contagion",
      "Incentives in Finance",
      "Capital Allocation",
      "Behavioural Finance",
    ],
    "Environmental Science": [
      "Climate & Energy Systems",
      "Biodiversity & Ecosystem Services",
      "Pollution & Its Effects",
      "Resource Depletion & Sustainability",
      "Human Impact on Nature",
      "Conservation & Restoration",
      "Environmental Justice",
      "The Carbon Cycle",
      "Tipping Points & Resilience",
      "Technological Solutions to Environmental Problems",
    ],
  },
};
